site_name: Documentación Plone v6.0
use_directory_urls: true
repo_url: https://github.com/rber474/plone6-docs
repo_name: rber474/plone6-docs
copyright: Copyright &copy; 2023 - 2027 Rafael Bermúdez Horcajada
extra:
  generator: false
theme:
  name: material
  language: es
  features:
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

